summer techtalk report
womendotcodebe/guest-blogs pull request #2
Opened 2022-08-09 16:35 UTC by federica-buzzi

2022-08-09 17:38 UTC, Mangamaui requested changes
Good work! 

I did add some comments to what might need to be changed.
Apart from that I think the only thing that might be missing is an endword :)

2022-08-09 17:38 UTC, Mangamaui commented on recap-of-techtalks-summer-edition-2021.md
> +Buckle up for the recap of another eclectic Techtalk.
Maybe turn int into "eclectic edition of our TechTalks"

2022-08-09 17:38 UTC, Mangamaui commented on recap-of-techtalks-summer-edition-2021.md
> +Let’s break the IT industry into its component to understand why it has such a big ecological impact.There are three main actors in IT:
its component <> smaller components?

2022-08-09 17:38 UTC, Mangamaui commented on recap-of-techtalks-summer-edition-2021.md
> +1. The manufacture of equipments
Lose the s at the end of equipment

2022-08-09 17:38 UTC, Mangamaui commented on recap-of-techtalks-summer-edition-2021.md
> +2. The manufacture of electricity
Not sure if manufacture is the right word here.

The process of generating electricity?

2022-08-09 17:38 UTC, Mangamaui commented on recap-of-techtalks-summer-edition-2021.md
> +Even if data centres conjure the image of the most energy-consuming part of IT industry, it is the end user devices that are responsible for most of the environmental impact - and especially their ma
centres <> centers

2022-08-09 17:38 UTC, Mangamaui commented on recap-of-techtalks-summer-edition-2021.md
> +Even if data centres conjure the image of the most energy-consuming part of IT industry, it is the end user devices that are responsible for most of the environmental impact - and especially their ma
Depending if you use british English or American English throughout the recap :)

2022-08-09 17:38 UTC, Mangamaui commented on recap-of-techtalks-summer-edition-2021.md
> +As citizens we can strive towards a digital sobriety approach: try to buy less equipment which lasts longer and is really useful.
This is a bit of a confusing sentence. Now it sounds like you should buy less equipment that lasts longer and is really useful. 

But I think you're trying to say that we should buy less equipment, but when we do it should focus on something that lasts longer and is really useful, no?

2022-08-09 17:38 UTC, Mangamaui commented on recap-of-techtalks-summer-edition-2021.md
> +We could choose to eco-design a digital service, which means trying to decrease its environmental impact by improving its conception and realisation. Which is basically a twofold operation: on one ha
conception <> concept

2022-08-09 17:38 UTC, Mangamaui commented on recap-of-techtalks-summer-edition-2021.md
> +#### Asma Oualmakran - Application security: Finding your way through buzzwords
wrong header, should be a h2


Best to review all headers for Asma's talk

2022-08-09 17:38 UTC, Mangamaui commented on recap-of-techtalks-summer-edition-2021.md
> +## Liza Morrison - Be Qwick, don’t ship JavaScript
Qwick should be Qwik (you repeated the typo throughout the recap)

2022-08-13 15:01 UTC, Mangamaui commented on recap-of-techtalks-summer-edition-2021.md
> +When a website scores poorly on performance the blame falls on the the developer, but what is it was the framework’s fault instead?
A typo: "but what is" should be what if

2022-08-15 08:15 UTC, Mangamaui approved these changes

2022-08-15 08:17 UTC, merged

2022-08-15 08:46 UTC, Mangamaui commented
@federica-buzzi A bit of extra feedback: 
- In the future if you use PDF's don't add them with the image script tags, this will result in several issues with the image optimisation script that is in place. You can add regular html tags in Markdown instead. But in this case it's probably better not to use PDF.

- In the future please add some comments for the parts I still need to fill in 😅 (for example the speaker images) otherwise I might forget.

I am currently doing a final check locally before your recap goes life, so don't push any more changes! :)

2022-08-15 11:35 UTC, federica-buzzi commented
gotcha!